### ISSUE TITLE
Error building whl

### ISSUE THREAD

**Issue by NaoufalRahali** [closeio/ciso8601#122] opened 2022-04-28 18:07 UTC
Building wheel for ciso8601 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ciso8601 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'ciso8601/__init__.py' not found (or not a regular file)
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/ciso8601
      copying ciso8601/__init__.pyi -> build/lib.linux-x86_64-cpython-38/ciso8601
      copying ciso8601/py.typed -> build/lib.linux-x86_64-cpython-38/ciso8601
      running build_ext
      building 'ciso8601' extension
      creating build/temp.linux-x86_64-cpython-38
      gcc -pthread -B /opt/anaconda3/envs/pycaret2/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/anaconda3/envs/pycaret2/include -fPIC -O2 -isystem /opt/anaconda3/envs/pycaret2/include -fPIC -DCISO8601_VERSION=2.2.0 -DCISO8601_CACHING_ENABLED=1 -I/opt/anaconda3/envs/pycaret2/include/python3.8 -c module.c -o build/temp.linux-x86_64-cpython-38/module.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ciso8601
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=ebe21d7f4f3048e4ebffc47954f8d0c8b25f65b8da88d210f1e149f19c7125f6
  Stored in directory: /root/.cache/pip/wheels/7f/1a/65/84ff8c386bec21fca6d220ea1f5498a0367883a78dd5ba6122
Successfully built antlr4-python3-runtime dtreeviz dash-auth emoji ffmpy python-multipart lime retrying pyperclip
Failed to build ciso8601
ERROR: Could not build wheels for ciso8601, which is required to install pyproject.toml-based projects

**Comment by movermeyer** [comment] 2022-04-28 18:53
Duplicate of #98. See [this comment](https://github.com/closeio/ciso8601/issues/98#issuecomment-720875244) for explanation.

**Closed by movermeyer** 2022-04-28 18:53 UTC
