### ISSUE TITLE
Unable to find method when using AWS Lambda

### ISSUE THREAD

**Issue by mobh13** [closeio/ciso8601#89] opened 2020-04-02 15:47 UTC
hello, so I used  ciso8601 in a lambda function but I cannot use it because it is returning this error 

```json
{
    "errorMessage": "module 'ciso8601' has no attribute 'parse_datetime'",
    "errorType": "AttributeError",
    "stackTrace": [
        "  File \"/var/task/convertToUnix/function.py\", line 14, in lambda_handler\n    'date': convert(event['date'])\n",
        "  File \"/var/task/convertToUnix/function.py\", line 5, in convert\n    s = ciso8601.parse_datetime(text)\n"
    ]
}
```

this is the code 

```python
import json
import ciso8601
import  time
def convert(text):
    s = ciso8601.parse_datetime(text)
    return time.mktime(s.timetuple())

def lambda_handler(event, context):
    if event['date'] != None:
        response = {
           'date': convert(event['date'])
        }
    else:
        response = {
             'message':"error no passed date"
         }
    return response
```

**Comment by movermeyer** [comment] 2020-04-03 01:39
Hello @mobh13,

I have not been able to reproduce this issue. I have created a Lambda using the above code and it worked fine.

------

Here are the steps I took:

### Prerequisites

* [AWS CLI tool](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html)

### Create the Lambda

* Go to the AWS lambda web console and [create a function](https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/function)
    * Choose "Author form scratch"
    * For this example, I used the name `ciso8601`
    * For this example, I used the `Python 3.8` Runtime
    * Click `Create function`

### Update the Lambda

Going to a bash shell (I used Ubuntu for Windows Subsystem for Linux (WSL)):

```bash
# Make sure you are using the same Python version as the AWS Lambda Runtime
python3.8 --version

# New directory to work in
mkdir ciso8601_lambda
cd ciso8601_lambda

# Create lambda_function.py with the contents you sent in your issue

# Optional: create a virtualenv (to make sure I am using the right pip)
python3.8 -m venv env

# Optional: Make sure pip is up to date
env/bin/pip install -U pip

# Install the ciso8601 dependency
env/bin/pip install --target ./package ciso8601

# Package everything into a AWS Lambda Deployment Package (https://docs.aws.amazon.com/lambda/latest/dg/python-package.html)
cd package
zip -r9 ../function.zip .
cd ..
zip -g function.zip lambda_function.py

# Upload the deploy package to AWS Lambda
aws lambda update-function-code --function-name ciso8601 --zip-file fileb://function.zip
```

### Run the Lambda

Going back to the AWS Lambda web console:

* [Look at the function](https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/ciso8601)
* Click `Test`
* Set `Event Name`, I used `BasicParse`
* Set the event payload to:
    ```json
    {
      "date": "2020-04-02T21:35:32Z"
    }
    ```
* Click `Create`
* Click `Test`

![image](https://user-images.githubusercontent.com/1459385/78315164-c2d5a600-754b-11ea-81bb-8e4ced184849.png)

**Comment by mobh13** [comment] 2020-04-03 01:45
ok thank you

**Comment by openbufo** [comment] 2020-06-09 21:14
The issue mentioned by @mobh13 is quite legit. The issue is observed on building AWS Lambda package on Mac. AWS lambda expects dependencies to be built and run on their AWS Linux, and for python, that means your dependencies need to support the `manylinux1 `wheel. 
AWS support page provides an easy [solution](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-package-compatible/) However ciso8601 pypi page doesn't have manylinux1 wheel.

@movermeyer Can you please provide a relevant wheel to extend support on Mac?

**Comment by movermeyer** [comment] 2022-12-21 21:03
v2.3.0 was just released with pre-built wheels for many platforms. 🎉

Give it a shot and let us know if you see any issues.

**Closed by movermeyer** 2022-12-21 21:03 UTC
Labels: binary wheels
